spring.application.name=errSense

errSense.bitbucket.baseUrl=

#spring.datasource.url=jdbc:h2:mem:errSense
#spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/errSense
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true