spring.application.name=errSense

errSense.bitbucket.baseUrl=

spring.datasource.url=jdbc:h2:mem:errSense
spring.datasource.driver-class-name=org.h2.Driver

# Flyway 默认会在 classpath:db/migration 目录下读取 SQL 脚本
spring.flyway.enabled=true